In [1]:
import os

# Create main project folder
os.makedirs("Energy_Project/data", exist_ok=True)
os.makedirs("Energy_Project/notebooks", exist_ok=True)
os.makedirs("Energy_Project/dashboard", exist_ok=True)
os.makedirs("Energy_Project/outputs", exist_ok=True)

# Create README file
with open("Energy_Project/README.md", "w") as f:
    f.write("# Hybrid Solar-Diesel-Battery Energy Optimization Project\n")

print("Project structure created successfully!")

Project structure created successfully!

In [8]:
import os

print(os.listdir("Energy_Project/data"))

['abuja_solar_2025.csv']

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
solar = pd.read_csv(
    "Energy_Project/data/abuja_solar_2025.csv",
    skiprows=9
)

In [15]:
solar.head()

   YEAR  MO  DY  ALLSKY_SFC_SW_DWN
0  2025   1   1             5.9369
1  2025   1   2             5.9450
2  2025   1   3             5.5214
3  2025   1   4             5.6784
4  2025   1   5             5.9743

In [17]:
system_size = 5 #KW

In [19]:
solar["Solar_Output"] = (
    solar["ALLSKY_SFC_SW_DWN"] * system_size
)

In [20]:
solar.head()

   YEAR  MO  DY  ALLSKY_SFC_SW_DWN  Solar_Output
0  2025   1   1             5.9369       29.6845
1  2025   1   2             5.9450       29.7250
2  2025   1   3             5.5214       27.6070
3  2025   1   4             5.6784       28.3920
4  2025   1   5             5.9743       29.8715

In [22]:
solar["Load_kWh"] = 40 #KW/day

In [24]:
#Energy gap (Demand - Solar)
solar["Energy_Gap"] = (
    solar["Load_kWh"] - solar["Solar_Output"]
)

solar[
    ["Solar_Output",
     "Load_kWh",
     "Energy_Gap"]
].head()

   Solar_Output  Load_kWh  Energy_Gap
0       29.6845        40     10.3155
1       29.7250        40     10.2750
2       27.6070        40     12.3930
3       28.3920        40     11.6080
4       29.8715        40     10.1285